# This is a basic workflow to help you get started with Actions

name: Liquibase_CLI_GitHub-Hosted

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "LBCIJob"
  dev_deployment_db:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: DEV

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: my-github-actions-role
      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: abhilash1in/aws-secrets-manager-action@v2.1.0
        with:
          secrets: |
            DB_USERNAME
            DB_URL
            DB_PASSWORD
          parse-json: true

      - name: Run a install and run Liquibase
        run: |
          echo Downloading Liquibase ...
          curl -L https://github.com/liquibase/liquibase/releases/download/v${LB_VERSION}/liquibase-${LB_VERSION}.zip --output liquibase-${LB_VERSION}.zip
          
          echo Unzipping liquibase-${LB_VERSION}.zip file ...
          unzip -o -q -d liquibase liquibase-${LB_VERSION}.zip
          export PATH=`pwd`/liquibase:${PATH}

          cd ${BASEDIR}

          # Using GitHub actions instead of defaultsFile
          # export LB_ARGS="--defaultsFile=${GITHUB_REF_NAME}.liquibase.properties --changelogFile=${CHANGELOGFILE} --classpath=${CLASSPATH}"


          echo DB_URL=${DB_URL}
          echo export
          export
          liquibase --version
          # liquibase ${LB_ARGS} status --verbose
          # liquibase ${LB_ARGS} updateSQL
          # liquibase ${LB_ARGS} update
          # liquibase ${LB_ARGS} history
          
        env:
            LB_VERSION: "4.11.0"
            LIQUIBASE_COMMAND_CHANGELOG_FILE: "masterchangelog.xml"
            BASEDIR: "src/sqlcode"    
            LIQUIBASE_CLASSPATH: "postgresql-42.2.23.jar"
            LIQUIBASE_HUB_MODE: "off"
            LIQUIBASE_PRO_LICENSE_KEY: ${{ secrets.LIQUIBASE_KEY }}


